name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  release:
    types: [published]

jobs:
  pre-commit:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pre-commit hooks
        uses: pre-commit/action@v3.0.1

  build:
    needs: pre-commit

    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        python-version: ["3.12"]

    defaults:
      run:
        shell: bash -l {0}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: dev-tools/conda-envs/ci_env.yaml
          environment-name: gha-test-env
          cache-environment: true
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Install fes-ml
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install .

      - name: Install test suite
        run: |
          python3 -m pip install pytest pytest-cov

      - name: Build coverage file
        run: |
          python3 -m pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=fes_ml | tee pytest-coverage.txt

      - name: Pytest coverage comment
        id: coverage-comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml

      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 4e01061daef80d7212844cc9cd272a01
          filename: fes_ml_pytest_coverage_report_main.json
          label: Coverage Report
          message: ${{ steps.coverage-comment.outputs.coverage }}
          color: ${{ steps.coverage-comment.outputs.color }}
          namedLogo: python

  # release:
  #   needs: build
  #   if: startsWith(github.ref, 'refs/tags')

  #   strategy:
  #     matrix:
  #         os: [ubuntu-latest]
  #         python-version: ["3.12"]

  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ matrix.python-version }}

  #     - name: Install release dependencies
  #       run: |
  #         python3 -m pip install --upgrade pip
  #         python3 -m pip install build --user

  #     - name: Generate distribution archives
  #       run: python3 -m build --sdist --wheel --outdir dist/

  #     - name: Publish distrbution to TestPyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         password: ${{ secrets.TEST_PYPI_API_TOKEN   }}
  #         repository_url: https://test.pypi.org/legacy/

  #     - name: Publish distribution to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         password: ${{ secrets.PYPI_API_TOKEN }}
